// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTegw3VrUCfi8rh-5iXn9jsgb_YLPCNc',
    appId: '1:398290487719:web:17e406edb1048386f3ce82',
    messagingSenderId: '398290487719',
    projectId: 'news-app-e4a4e',
    authDomain: 'news-app-e4a4e.firebaseapp.com',
    storageBucket: 'news-app-e4a4e.firebasestorage.app',
    measurementId: 'G-1DF0L50S5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDepHuZngeoEghxkHu01Cpf879dHfZeNyo',
    appId: '1:398290487719:android:909416d4daab4d1af3ce82',
    messagingSenderId: '398290487719',
    projectId: 'news-app-e4a4e',
    storageBucket: 'news-app-e4a4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7-ICI0lgrZzBQ55gZ1alsDBrzBZO3Tk',
    appId: '1:398290487719:ios:37279416af9cbad1f3ce82',
    messagingSenderId: '398290487719',
    projectId: 'news-app-e4a4e',
    storageBucket: 'news-app-e4a4e.firebasestorage.app',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxTegw3VrUCfi8rh-5iXn9jsgb_YLPCNc',
    appId: '1:398290487719:web:0a1fb22de7a573c6f3ce82',
    messagingSenderId: '398290487719',
    projectId: 'news-app-e4a4e',
    authDomain: 'news-app-e4a4e.firebaseapp.com',
    storageBucket: 'news-app-e4a4e.firebasestorage.app',
    measurementId: 'G-F2YKTZ3SRD',
  );
}
